# Generated by Django 5.1.2 on 2024-11-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teaminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
